language: python
cache: pip
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install 'coverage<4'
  - pip install coveralls
script: nosetests
after_success: coveralls
